---
ssh_keys:
  ecdsa:
    public: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFTK3OXpgKNDPkK6UWQBdLIPQuRtq4gQ2gd03HgMgaP9LYvy+Pvfj6raInxjZBkpXJ1w8o2qf2KPhazpL6zEsMs= '
    private: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
      1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQRUytzl6YCjQz5CulFkAXSyD0LkbauI
      ENoHdNx4DIGj/S2L8vj734+q2iJ8Y2QZKVydcPKNqn9ij4Ws6S+sxLDLAAAAoFV5brpVeW
      66AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFTK3OXpgKNDPkK6
      UWQBdLIPQuRtq4gQ2gd03HgMgaP9LYvy+Pvfj6raInxjZBkpXJ1w8o2qf2KPhazpL6zEsM
      sAAAAhANwBoWNI4O/+tce9IFDxQlT8XLMN5L+6ocDQelwDFPOWAAAAAAECAwQFBgc=
      -----END OPENSSH PRIVATE KEY-----
  ed25519:
    public: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwZjZU/Ro8Zv6Do6zAY3wYfsUQJyfWIfHtcDO6kND9D '
    private: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACCcGY2VP0aPGb+g6OswGN8GH7FECcn1iHx7XAzupDQ/QwAAAIixBoHtsQaB
      7QAAAAtzc2gtZWQyNTUxOQAAACCcGY2VP0aPGb+g6OswGN8GH7FECcn1iHx7XAzupDQ/Qw
      AAAEAPDdchldzqwKDI97OAydQfcZUiNVkPDFoLOMBEgepEMZwZjZU/Ro8Zv6Do6zAY3wYf
      sUQJyfWIfHtcDO6kND9DAAAAAAECAwQF
      -----END OPENSSH PRIVATE KEY-----
  rsa:
    public: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9AzqCFypWIr5rPuKrmokOANCSO3jhknI47FwVv/tN9NhU8acFmimDx42KkW4ImpP/QTFDOb+RSrc20mxrrCsyJdAYsXVf4o+831a2qIBXY/psd8iQ5kht88vAouLe4B8652xZexcWU+iqPQl+yQcbDhuoUKb0nF2QpAIShcW32WNGCKNjzDE+o9tdSu7C5nMKBo2npE+rBDafEzCu4RcWvu1sWenOxV2B2XSSDFvQ3NjVIYT9cV3Idd8uGIaUu8yr0vdh7gwZ0013VVZ7rg19/ATIEVs9zTf6JByPvmglDZ5woE5PEfq3WVE5GLCMy8eOb3LHmTLMNWzjEHKI7HEXwCTezA3WYR+PadGplIzAufiO1yOsklGjPrncc/sUNgFBs7DM6Q9Hkp/p740v3SuSxmqZyvord7X7g7evx8BpJ+RF1lYz18NcAHWyY3wtV4qCy0gK3P+tlkJVV/5L2IESAmGoyMKl11ruI8QjSPrkRQyhbtnhI5tpZwAD1EofzTU= '
    private: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEAvQM6ghcqViK+az7iq5qJDgDQkjt44ZJyOOxcFb/7TfTYVPGnBZop
      g8eNipFuCJqT/0ExQzm/kUq3NtJsa6wrMiXQGLF1X+KPvN9WtqiAV2P6bHfIkOZIbfPLwK
      Li3uAfOudsWXsXFlPoqj0JfskHGw4bqFCm9JxdkKQCEoXFt9ljRgijY8wxPqPbXUruwuZz
      CgaNp6RPqwQ2nxMwruEXFr7tbFnpzsVdgdl0kgxb0NzY1SGE/XFdyHXfLhiGlLvMq9L3Ye
      4MGdNNd1VWe64NffwEyBFbPc03+iQcj75oJQ2ecKBOTxH6t1lRORiwjMvHjm9yx5kyzDVs
      4xByiOxxF8Ak3swN1mEfj2nRqZSMwLn4jtcjrJJRoz653HP7FDYBQbOwzOkPR5Kf6e+NL9
      0rksZqmcr6K3e1+4O3r8fAaSfkRdZWM9fDXAB1smN8LVeKgstICtz/rZZCVVf+S9iBEgJh
      qMjCpdda7iPEI0j65EUMoW7Z4SObaWcAA9RKH801AAAFeHKm3FJyptxSAAAAB3NzaC1yc2
      EAAAGBAL0DOoIXKlYivms+4quaiQ4A0JI7eOGScjjsXBW/+0302FTxpwWaKYPHjYqRbgia
      k/9BMUM5v5FKtzbSbGusKzIl0BixdV/ij7zfVraogFdj+mx3yJDmSG3zy8Ci4t7gHzrnbF
      l7FxZT6Ko9CX7JBxsOG6hQpvScXZCkAhKFxbfZY0YIo2PMMT6j211K7sLmcwoGjaekT6sE
      Np8TMK7hFxa+7WxZ6c7FXYHZdJIMW9Dc2NUhhP1xXch13y4YhpS7zKvS92HuDBnTTXdVVn
      uuDX38BMgRWz3NN/okHI++aCUNnnCgTk8R+rdZUTkYsIzLx45vcseZMsw1bOMQcojscRfA
      JN7MDdZhH49p0amUjMC5+I7XI6ySUaM+udxz+xQ2AUGzsMzpD0eSn+nvjS/dK5LGapnK+i
      t3tfuDt6/HwGkn5EXWVjPXw1wAdbJjfC1XioLLSArc/62WQlVX/kvYgRICYajIwqXXWu4j
      xCNI+uRFDKFu2eEjm2lnAAPUSh/NNQAAAAMBAAEAAAGBAI0kmw1IFTJLMZzOUd/JP204iI
      eaZ5Myk58USVNokFXPb7hG1+1kCHpCityd6uf73mZvHUVRG0941sXWbmYdJAiHmhTGd5rJ
      iYKF2K//tg8MNpXHAPvLKu0Ib++C8x1xiYCoDg3nz/65W/W8LJoDrg2zBE41I+dn2KrI/k
      8sm8/FQs+qZbCBa4iWPZo1+YOLKP6klCVKmr9fHxa88s60gVRX8N3HasQgN8peQyFIn0uh
      jz3gkPndLSYjdyxp3h20+kBPPywvGzmej5i8AoJedaPCuV1Ex95lmNVkqYjKuR2SoIgSSn
      lTmKhSvZ4TN/cIXruuoJEnd461R6Ne6yZzYyqX7Z3Mf8FzEWomBHMPKKjr8n4WRTEqD+kz
      DZ81UkJBZDALXoznSrFTOerVKJD21RuWUJTwh6sN4bgmdtX9bCHgJmDct5bMAF4xR9aLt9
      B7InxjXKyTZY7dSJ7my3Oot93wxnMS3B70TN75AslGcUiwGYb669Y0sIM7kWrJCggrJQAA
      AMEAnA3OSGkSwrNtdeln6AI/7Mt1R4QNl9F4/37N0vZCnUoyOJBNUjhez1aEplh0KN93dl
      pdpzsKwylDERoFZl6jYI/XkWQhLbV7cou4oIcRRF9O1PO0tBtofWZfxNK1VXK9Ckrurgye
      TPzRAKBKM4XEka41Z/ah+Isl2lEHf2TbjSTtufmpq3jvxSG9iwqcPd9f3X+DB6tfTn45dc
      fpm7HCs+wZh7KnSOOR0bPDvraurBmRx8hsWhOx7HgfyjguKhGGAAAAwQDz9dn/e9HaYSGN
      Gj8DwNSO05UKvZxnMXW495nv4z6fXT7NJm7PQWSedq+NI4POPDroUD4LzCxo5v7noSiAk9
      SdgrpJ+UhufHma9YFbUboTE3w8FwyXtGstW7ZUHkCr5W3iAf/cYELnZYRakB7loyZp0H7Z
      Dcaaz9ymMCuKV1MYVfVdjfdU+yT+554LNz8GJOn4kcZ3nzUTvryeAilGj6XArgg/B1tGJd
      bJHAwO4ZeOmWlKwik9+e/xjCcpH+XJTj8AAADBAMZXLX0SDwPZrR6BnAp+h3SkCLBZJ1JI
      VryTajbWUERG0RBgQQSCXgLFkYJF0NGUM3Rvmu12vbfJs5vPIP5Tcexj7QXlY/05Np37zy
      g3ztVG+HnFBtpIkgffrr3r6xGHbk39TrMvnfqMeQhS18sbIXZ3VxooQC3e2/7nbY2Pl7oj
      uqT0N5PrW9RcSRlCD4xW5igXgnGfEQDuGMeR9JUGwp+5ILGzeP4nadYlsv5hUTAICY6iK+
      EMSepnJk18c9tviwAAAAAB
      -----END OPENSSH PRIVATE KEY-----
